<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BrightEdu.Domain\BrightEdu.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="DTOs\LessonCreationModel.cs" />
      <Compile Remove="Interfaces\ILessonStepDtoMapper.cs" />
      <Compile Remove="Interfaces\IGetTemplateAsCreationModelService.cs" />
      <Compile Remove="Interfaces\ICreateLessonWithPrototypeService.cs" />
      <Compile Remove="Interfaces\ICreateLessonWithFactoryMethodService.cs" />
      <Compile Remove="Interfaces\ICreateLessonWithBuilderService.cs" />
      <Compile Remove="Interfaces\ICreateLessonWithAdapterService.cs" />
      <Compile Remove="Interfaces\ICreateLessonWithAbstractFactoryService.cs" />
      <Compile Remove="Interfaces\ICreateLessonService.cs" />
      <Compile Remove="Interfaces\IBuildLessonCompositeService.cs" />
      <Compile Remove="Interfaces\ICreateLessonFromTemplateService.cs" />
      <Compile Remove="Interfaces\ICourseRepository.cs" />
      <Compile Remove="Features\Lessons\Mapper\**" />
      <Compile Remove="Features\Lessons\CreateLessonWithAbstractFactoryService.cs" />
      <Compile Remove="Features\Lessons\CreateLessonWithAdapterService.cs" />
      <Compile Remove="Features\Lessons\CreateLessonWithBuilderService.cs" />
      <Compile Remove="Features\Lessons\CreateLessonWithFactoryMethodService.cs" />
      <Compile Remove="Features\Lessons\CreateLessonWithPrototypeService.cs" />
      <Compile Remove="Features\Lessons\GetTemplateAsCreationModelService.cs" />
      <Compile Remove="DesignPatterns\Singleton\**" />
      <Compile Remove="DesignPatterns\FactoryMethod\**" />
      <Compile Remove="DesignPatterns\Facade\**" />
      <Compile Remove="DesignPatterns\Composite\**" />
      <Compile Remove="DesignPatterns\Builder\**" />
      <Compile Remove="DesignPatterns\Adapter\**" />
      <Compile Remove="DesignPatterns\AbstractFactory\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Features\Lessons\Mapper\**" />
      <EmbeddedResource Remove="DesignPatterns\Singleton\**" />
      <EmbeddedResource Remove="DesignPatterns\FactoryMethod\**" />
      <EmbeddedResource Remove="DesignPatterns\Facade\**" />
      <EmbeddedResource Remove="DesignPatterns\Composite\**" />
      <EmbeddedResource Remove="DesignPatterns\Builder\**" />
      <EmbeddedResource Remove="DesignPatterns\Adapter\**" />
      <EmbeddedResource Remove="DesignPatterns\AbstractFactory\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Features\Lessons\Mapper\**" />
      <None Remove="DesignPatterns\Singleton\**" />
      <None Remove="DesignPatterns\FactoryMethod\**" />
      <None Remove="DesignPatterns\Facade\**" />
      <None Remove="DesignPatterns\Composite\**" />
      <None Remove="DesignPatterns\Builder\**" />
      <None Remove="DesignPatterns\Adapter\**" />
      <None Remove="DesignPatterns\AbstractFactory\**" />
    </ItemGroup>

</Project>
